"""add identity document_hash

Revision ID: 4a5ab4e5d446
Revises: a721847261ad
Create Date: 2026-06-15 18:14:02.991659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a5ab4e5d446'
down_revision: Union[str, Sequence[str], None] = 'a721847261ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('document_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_identities_document_hash'), ['document_hash'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_document_hash'))
        batch_op.drop_column('document_hash')

    # ### end Alembic commands ###
