"""add revoked_credentials

Revision ID: 7244caf88a59
Revises: 93c0d6beaf4b
Create Date: 2026-06-15 11:20:51.673301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7244caf88a59'
down_revision: Union[str, Sequence[str], None] = '93c0d6beaf4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('revoked_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('identity_hash', sa.String(length=64), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revoked_credentials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revoked_credentials_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_credentials_identity_hash'), ['identity_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_revoked_credentials_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('revoked_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revoked_credentials_jti'))
        batch_op.drop_index(batch_op.f('ix_revoked_credentials_identity_hash'))
        batch_op.drop_index(batch_op.f('ix_revoked_credentials_created_at'))

    op.drop_table('revoked_credentials')
    # ### end Alembic commands ###
