"""initial schema

Revision ID: 93c0d6beaf4b
Revises: 
Create Date: 2026-06-15 11:06:51.085227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93c0d6beaf4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_subject'), ['subject'], unique=False)

    op.create_table('identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('biometric_template', sa.JSON(), nullable=False),
    sa.Column('limit_usdc', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_identities_identity_hash'), ['identity_hash'], unique=True)

    op.create_table('ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('amount_usdc', sa.Float(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key', name='uq_ledger_idempotency')
    )
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ledger_identity_id'), ['identity_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_pubkey', sa.String(length=128), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('email_hash', sa.String(length=64), nullable=True),
    sa.Column('device_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['identity_id'], ['identities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_country'), ['country'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_device_fingerprint'), ['device_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email_hash'), ['email_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_phone_hash'), ['phone_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_wallet_pubkey'), ['wallet_pubkey'], unique=True)

    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('started', 'documents_submitted', 'biometrics_submitted', 'pending_review', 'approved', 'rejected', name='sessionstatus'), nullable=False),
    sa.Column('signals', sa.JSON(), nullable=False),
    sa.Column('decision', sa.Enum('approve', 'review', 'reject', name='decision'), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('reject_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolution', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_queue')
    op.drop_table('sessions')
    # Postgres materializes native ENUM types for the status/decision columns;
    # drop_table leaves them behind, so remove them explicitly. On SQLite (where
    # enums are stored as VARCHAR) these calls are no-ops.
    sa.Enum(name='sessionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='decision').drop(op.get_bind(), checkfirst=True)
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_wallet_pubkey'))
        batch_op.drop_index(batch_op.f('ix_users_phone_hash'))
        batch_op.drop_index(batch_op.f('ix_users_email_hash'))
        batch_op.drop_index(batch_op.f('ix_users_device_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_users_country'))

    op.drop_table('users')
    with op.batch_alter_table('ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ledger_identity_id'))

    op.drop_table('ledger')
    with op.batch_alter_table('identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_identities_identity_hash'))

    op.drop_table('identities')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_subject'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_log_action'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
