"""add media_objects

Revision ID: a721847261ad
Revises: 7244caf88a59
Create Date: 2026-06-15 11:40:02.889415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a721847261ad'
down_revision: Union[str, Sequence[str], None] = '7244caf88a59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_objects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('storage_ref', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_objects_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_objects_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_media_objects_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media_objects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_objects_session_id'))
        batch_op.drop_index(batch_op.f('ix_media_objects_kind'))
        batch_op.drop_index(batch_op.f('ix_media_objects_expires_at'))

    op.drop_table('media_objects')
    # ### end Alembic commands ###
